replicaCount: 1
appName: chainlink-node
project: avian-direction-235610

deployment:
  name: chainlink-deployment

container:
  name: chainlink
  port: 6688
  configEnv: node-env

loadbalancer:
  port: 8068

image:
  repository: smartcontract/chainlink:1.3.0
  pullPolicy: IfNotPresent

volume:
  apiMountName: api-volume
  apiMountPath: /chainlink/.api
  apiMountSubPath: .api
  apiSecretName: api-env
  passwordMountName: password-volume
  passwordMountPath: /chainlink/.password
  passwordMountSubPath: .password
  passwordSecretName: password-env

secrets:
  extSecretsEnv: external-secrets-env
  extSecretsApi: external-secrets-api
  extSecretsApiKey1: .api
  extSecretsApiKey2: .password
  extSecretsStoreEnv: external-secret-store-env
  extSecretsStoreApi: external-secret-store-api
  extGCPSecretsStoreApi: BINANCE_KEEPER_API
  extGCPSecretsStorePassword: BINANCE_KEEPER_PASSWORD
  gcpsmSecretEnv: gcpsm-secret-env
  gcpsmSecretApi: gcpsm-secret-api
  secretAccessCredentials: secret-access-credentials

configMap:
  keeper:
    ROOT: '/chainlink'
    ETH_CHAIN_ID: '56'
    CHAINLINK_TLS_PORT: '0'
    SECURE_COOKIES: 'false'
    ALLOW_ORIGINS: '*'
    BLOCK_HISTORY_ESTIMATOR_TRANSACTION_PERCENTILE: '80'
    KEEPER_MINIMUM_REQUIRED_CONFIRMATIONS: '200'
    KEEPER_REGISTRY_PERFORM_GAS_OVERHEAD: '300000'
    ETH_SECONDARY_URLS: 'https://nop:sppFRFaNtD9qUQgNHoK6LUdFwuHGhv@multichain.broadcast-mirror.chain.link/?chain_id=56'
    ETH_URL: 'wss://mainnet.binance-smart-chain.api.fiews.io/v2/ws/AWtDsb4iMRQbeEQRhHiFkK9d7MmRNR1pg0aucjit'
    ETH_HTTP_URL: 'https://mainnet.binance-smart-chain.api.fiews.io/v2/rpc/AWtDsb4iMRQbeEQRhHiFkK9d7MmRNR1pg0aucjit'
    #DATABASE_LOCKING_MODE : 'lease'

configMapSecrets:
  DATABASE_URL: DATABASE_URL
  LINK_CONTRACT_ADDRESS: LINK_CONTRACT_ADDRESS


remoteConfigMapSecrets:
  DATABASE_URL: BINANCE_KEEPER_DATABASE_URL
  LINK_CONTRACT_ADDRESS: BINANCE_KEEPER_LINK_CONTRACT_ADDRESS
