apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.gcpsmSecretEnv }}
  labels:
    type: gcpsm
type: Opaque
stringData:
  secret-access-credentials: |-
    {
      \\ Provide GCP service_accout details here
    }