apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ .Values.secrets.extSecretsStoreApi }}
spec:
  provider:
      gcpsm:                                  # gcpsm provider
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: {{ .Values.secrets.gcpsmSecretApi }}              # secret name containing SA key
              key: {{ .Values.secrets.secretAccessCredentials }}  # key name containing SA key
        projectID: {{ .Values.project }}                  # name of Google Cloud project