variable name {}
variable location {}
variable project {}
variable description {}
variable network {}
variable subnetwork {}
variable oauth_scopes {}
variable type {}
variable create {}
variable update {}